<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LIN66011991" failures="1" tests="3" name="OrangeHRM" time="17.375" errors="0" timestamp="2024-08-12T13:59:03 IST">
  <testcase classname="listerners.OrangeHRM" name="testLogo" time="0.078"/>
  <testcase classname="listerners.OrangeHRM" name="testAppURL" time="0.03">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/logi] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/logi] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at listerners.OrangeHRM.testAppURL(OrangeHRM.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testAppURL -->
  <testcase classname="listerners.OrangeHRM" name="testTitle" time="0.0">
    <skipped/>
  </testcase> <!-- testTitle -->
</testsuite> <!-- OrangeHRM -->
